import "./vendors";
import "./modules/_moving";
import "./modules/_defaults";
import "./modules/_form";
import "./modules/_accordion";
import "./modules/_gallery-slider";
import "./modules/_range-input";
import "./modules/_checkbox-list";
import "./modules/_select";
import "./modules/_filter";
import "./modules/_services";
import "./modules/_search";
import "./modules/_modals";
import "./modules/_tabs";
import "./modules/_quiz";
import "./modules/_submenu";
import "./modules/_mobile-list";
import "./modules/_sliders";
import "./modules/_reviews";
import "./modules/_sell-apartment";
import "./modules/_ba";
import "./modules/_sell-popup";
import "./modules/_open-comments";
import "./modules/_article-title";
import "./modules/_questions-mobile-popup";
import "./modules/_success-auction";
import "./modules/_news-tab";
import "./modules/_comments-blog";
import "./modules/_textarea";
import "./modules/_open-faq";
import "./modules/_scroll";
import "./modules/_sertificates";
import "./modules/_stiky-header";

import { background } from "./modules/_background";
background.init();
